# [[session]]
# name = "radium"
# path = "~"
#
[[session]]
name = "monitoring"
path = "~"
windows = ["ticker", "portfolio" ]


[[session]]
name = "Clankers"
path = "~/Projets/Clankers"
windows = ["opencode"]

[[window]]
name = "ticker"
startup_script = "ticker"

[[window]]
name = "portfolio"
startup_script = "portfolio"

[[window]]
name = "opencode"
startup_script = "opencode --agent chat"
