[[session]]
name = "Radium"
path = "~"
windows = ["btop"]

[[session]]
name = "Ticker"
path = "~"
windows = ["ticker", "portfolio" ]

[[session]]
name = "Clankers"
path = "~/Projets/Clankers"
windows = ["opencode"]

[[session]]
name = "Notes"
path = "~/Notes"
windows = ["notes"]

[[window]]
name = "btop"
startup_script = "btop"

[[window]]
name = "notes"
startup_script = "oq"

[[window]]
name = "ticker"
startup_script = "ticker"

[[window]]
name = "portfolio"
startup_script = "portfolio"

[[window]]
name = "opencode"
startup_script = "opencode --agent chat"
